<a href="https://colab.research.google.com/github/MatheusFriedrich06/AulaPCD_05/blob/main/AtividadePandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
#Importando um arquivo .csv dos dados de temperatura dos municípios
df = pd.read_csv('https://raw.githubusercontent.com/andr3nf/clima_municipios_brasileiros/refs/heads/main/clima_historico_municipal.csv')

In [7]:
cidade = df.loc[df['nome_municipio'] == 'Santa Rosa']

cidade

,codigo_ibge,nome_municipio,uf,periodo_inicio,periodo_fim,fonte_clima,metodo_processamento,temp_media_jan,temp_media_fev,temp_media_mar,...,def_mar,def_abr,def_mai,def_jun,def_jul,def_ago,def_set,def_out,def_nov,def_dez
4975,4317202,Santa Rosa,RS,1975,2024,TerraClimate,media_dos_pixels_do_raster_dentro_do_municipio...,25.3,25.01,23.41,...,20.58,9.17,3.34,0.44,1.33,6.04,5.83,4.35,21.7,37.1

In [9]:
deficit = cidade[[
    'def_jan', 'def_fev', 'def_mar', 'def_abr',
    'def_mai', 'def_jun', 'def_jul', 'def_ago',
    'def_set', 'def_out', 'def_nov', 'def_dez'
]]

mesMaiorDeficit = deficit.idxmax(axis=1)

mesMaiorDeficit

4975    def_jan
dtype: object

In [18]:
mediaVerao = cidade[
    ['temp_media_dez', 'temp_media_jan', 'temp_media_fev']
].mean(axis=1)

print(mediaVerao)

4975    24.976667
dtype: float64

In [16]:
mediaInverno = cidade[
    ['temp_media_jun', 'temp_media_jul', 'temp_media_ago']
].mean(axis=1)

print(mediaInverno)

4975    15.56
dtype: float64

In [14]:
mediaPrimavera = cidade[
    ['temp_media_set', 'temp_media_out', 'temp_media_nov']
].mean(axis=1)

print(mediaPrimavera)

4975    20.626667
dtype: float64

In [17]:
mediaOutono = cidade[
    ['temp_media_mar', 'temp_media_abr', 'temp_media_mai']
].mean(axis=1)

print(mediaOutono)

4975    20.283333
dtype: float64